# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('emailAddr', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=20)),
                ('locationPersonal', models.TextField(max_length=200)),
                ('locationTombstone', models.TextField(max_length=200)),
                ('howManyTombstones', models.IntegerField()),
                ('installationDate', models.CharField(max_length=120)),
                ('catalogueCodes', models.CharField(max_length=120)),
                ('colorTombstone', models.CharField(max_length=120)),
                ('otherInfo', models.TextField(max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
