# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbackFullname', models.CharField(max_length=120)),
                ('fbackContactNo', models.CharField(max_length=20)),
                ('fbackEmailAddr', models.CharField(max_length=200)),
                ('fbackType', models.CharField(max_length=5)),
                ('fbackMessage', models.TextField(max_length=1000)),
                ('fbackTimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
