# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fbackEmailAddr',
            field=models.EmailField(max_length=254),
        ),
    ]
