# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20160520_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fbackType',
            field=models.CharField(max_length=50),
        ),
    ]
