# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20160520_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('COMPLAINT', 'Complaint'), ('COMPLEMENT', 'Complement'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
