# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogueimages',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='catalogueimages',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
