# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160525_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueimages',
            name='desc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
