# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20160525_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueimages',
            name='image',
            field=models.ImageField(upload_to='images/catalogue'),
        ),
    ]
